###
### .travis.yml
###

sudo: false
os: linux
dist: trusty
language: node_js
node_js:
  - 'node'
  - '8'
  - '6'
  - '5'
  - '4'
env:
- NODE_ENV=development
notifications:
  slack:
    secure: fsCX0/TDE9TAJR0S91dboOZ4expmCc8o6joVzsHNJYTJfDtSJehdKjTzYuO/vsRigOOoQZ0dJEPl+D4fysBDV+jkOT5sTjp/uKtcfwHwPi03K8GauwvyW0x4N1M+mY+5jN2ZyBZXqVM5dc0wbgldP9QOg5UpB80hfWUZ+0F1MTM=
deploy:
  provider: npm
  email: kyan.ql.he@gmail.com
  api_key:
    secure: G58hf18DK3OzBUnSflTj9z4HPImAVxa9v/VKCvnG9gqaRyDtjoHweZWjzEu2K+ThtMOTbDCJx86KEOkHxKnjYPoXPbhHwK6LlfzRqv2rwsqkJLG0EirPecZA2aeTkxZBqf4camLIJY8GL9v0FiwB7CZ5QHlxhluhnZj+N6kPkaU=
  on:
    tags: true
    repo: cybertk/abao
after_success:
#  - grunt coveralls:upload
  - BUILD_DIR="$HOME/build"
  - GITHUB_REPO="cybertk/abao"
  - PROJ_BUILD_DIR="$BUILD_DIR/$GITHUB_REPO"
  - PROJ_COVER_DIR="$PROJ_BUILD_DIR/coverage"
  - COVERAGE_FILE="$PROJ_COVER_DIR/coverage.lcov"
  - COVERALLS_BIN="./node_modules/.bin/coveralls"
  - $COVERALLS_BIN < $COVERAGE_FILE; echo "exit=$?"

